name: yokapos
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.4.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  esc_pos_utils_plus: ^2.0.3
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.2.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  percent_indicator: ^4.2.4
  permission_handler: ^12.0.1
  print_bluetooth_thermal: ^1.1.6
  shared_preferences: ^2.5.1
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo/yokapos.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/logo/yokapos.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/logo/
    - assets/images/
    - assets/images/products/
    - assets/images/logo/
    - assets/fonts/noto-sans.ttf
